name: Build and publish latest image

on:
  workflow_dispatch:

env:
  IMAGE_NAME: odp-adapter
  DOCKERHUB_USERNAME: starwit
  DOCKERHUB_ORG: starwitorg   

jobs:
  build:
    name: "Build and publish with build number"
    runs-on: [self-hosted, linux, X64]

    steps:
    - name: checkout
      uses: actions/checkout@v4    

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 21

    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.5
      with:
        maven-version: 3.9.2

    - name: setup node
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - run: npm --version
    - run: node --version
    - run: mvn --version

    - name: get version from pom.xml
      run: |      
        echo "VERSION_BUILD=$( mvn help:evaluate -Dexpression=project.version -q -DforceStdout )-${{ github.run_number }}" >> $GITHUB_ENV
        echo "VERSION_JAR=$( mvn help:evaluate -Dexpression=project.version -q -DforceStdout )" >> $GITHUB_ENV

    - name: npm install
      run: |
        if [ -d "webclient/app" ]; then
          cd webclient/app
          npm install
        fi

    - name: Build with Maven
      run: mvn clean -B package --file pom.xml
      env:
         CI: false