name: PR Build

# PR build

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:


# just runs Maven, NPM and Docker build
jobs:
  build:
    name: "Install software"
    runs-on: [self-hosted, linux, X64]

    steps:
    - id: install-secret-key
      name: Install gpg secret key
      run: |
        # Install gpg secret key
        cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}") | gpg --batch --import
        # Verify gpg secret key
        gpg --list-secret-keys --keyid-format LONG    
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 21

    - name: Set up Maven
      uses: stCarolas/setup-maven@v5
      with:
         maven-version: 3.9.2        

    - name: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: '0'

    - name: Build with Maven
      run: mvn clean -B package --file pom.xml
      env:
         CI: false



